<?php

namespace ContainerIMMgl8V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDailydietController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Employe\DailydietController' shared autowired service.
     *
     * @return \App\Controller\Employe\DailydietController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Employe/DailydietController.php';

        $container->services['App\\Controller\\Employe\\DailydietController'] = $instance = new \App\Controller\Employe\DailydietController(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\Employe\\DailydietController', $container));

        return $instance;
    }
}
