<?php

namespace ContainerOYXQprz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NuhFOKnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NuhFOKn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NuhFOKn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'habitatreportepository' => ['privates', 'App\\Repository\\HabitatreportRepository', 'getHabitatreportRepositoryService', true],
        ], [
            'habitatreportepository' => 'App\\Repository\\HabitatreportRepository',
        ]);
    }
}
