<?php

namespace ContainerOYXQprz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZSL8qBoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZSL8qBo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZSL8qBo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vetreportepository' => ['privates', 'App\\Repository\\VetreportRepository', 'getVetreportRepositoryService', true],
        ], [
            'vetreportepository' => 'App\\Repository\\VetreportRepository',
        ]);
    }
}
