<?php

namespace ContainerETwPhIl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicesControllerdetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WNQSJs6.App\Controller\ServicesController::details()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WNQSJs6.App\\Controller\\ServicesController::details()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'service' => ['privates', '.errored..service_locator.WNQSJs6.App\\Entity\\Habitat', NULL, 'Cannot autowire service ".service_locator.WNQSJs6": it needs an instance of "App\\Entity\\Habitat" but this type has been excluded in "config/services.yaml".'],
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
        ], [
            'service' => 'App\\Entity\\Habitat',
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
        ]))->withContext('App\\Controller\\ServicesController::details()', $container);
    }
}
