<?php

namespace ContainerVyyQ5xy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestimonialControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ufefr24.App\Controller\Admin\TestimonialController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ufefr24.App\\Controller\\Admin\\TestimonialController::index()'] = ($container->privates['.service_locator.ufefr24'] ?? $container->load('get_ServiceLocator_Ufefr24Service'))->withContext('App\\Controller\\Admin\\TestimonialController::index()', $container);
    }
}
