<?php

namespace ContainerV9IXyW0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestimonialControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZKETimn.App\Controller\Admin\TestimonialController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZKETimn.App\\Controller\\Admin\\TestimonialController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'testimonial' => ['privates', '.errored..service_locator.ZKETimn.App\\Entity\\Testimonial', NULL, 'Cannot autowire service ".service_locator.ZKETimn": it needs an instance of "App\\Entity\\Testimonial" but this type has been excluded in "config/services.yaml".'],
        ], [
            'testimonial' => 'App\\Entity\\Testimonial',
        ]))->withContext('App\\Controller\\Admin\\TestimonialController::show()', $container);
    }
}
