<?php

namespace Container1j8T6gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WT0LS6tService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.wT0LS6t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wT0LS6t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Habitatreport' => ['privates', '.errored..service_locator.wT0LS6t.App\\Entity\\Habitatreport', NULL, 'Cannot autowire service ".service_locator.wT0LS6t": it needs an instance of "App\\Entity\\Habitatreport" but this type has been excluded in "config/services.yaml".'],
        ], [
            'Habitatreport' => 'App\\Entity\\Habitatreport',
        ]);
    }
}
