<?php

namespace Container1j8T6gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitatsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\HabitatsController' shared autowired service.
     *
     * @return \App\Controller\HabitatsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\HabitatsController'] = $instance = new \App\Controller\HabitatsController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\HabitatsController', $container));

        return $instance;
    }
}
