<?php

namespace Container1j8T6gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitatreportControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.2jYvYwd.App\Controller\Admin\HabitatreportController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.2jYvYwd'] ?? $container->load('get_ServiceLocator_2jYvYwdService'));

        if (isset($container->privates['.service_locator.2jYvYwd.App\\Controller\\Admin\\HabitatreportController::edit()'])) {
            return $container->privates['.service_locator.2jYvYwd.App\\Controller\\Admin\\HabitatreportController::edit()'];
        }

        return $container->privates['.service_locator.2jYvYwd.App\\Controller\\Admin\\HabitatreportController::edit()'] = $a->withContext('App\\Controller\\Admin\\HabitatreportController::edit()', $container);
    }
}
