<?php

namespace Container1j8T6gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitatreportService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.2jYvYwd.App\Entity\Habitatreport' shared service.
     *
     * @return \App\Entity\Habitatreport
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2jYvYwd": it needs an instance of "App\\Entity\\Habitatreport" but this type has been excluded in "config/services.yaml".');
    }
}
