<?php

namespace Container1j8T6gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ImageService' shared autowired service.
     *
     * @return \App\Service\ImageService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ImageService'] = new \App\Service\ImageService(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
