<?php

namespace Container1j8T6gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpeningTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\OpeningType' shared autowired service.
     *
     * @return \App\Form\OpeningType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\OpeningType'] = new \App\Form\OpeningType();
    }
}
