<?php

namespace Container1j8T6gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllershow2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.HQ6Z48r.App\Controller\Employe\ServiceController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HQ6Z48r.App\\Controller\\Employe\\ServiceController::show()'] = ($container->privates['.service_locator.HQ6Z48r'] ?? $container->load('get_ServiceLocator_HQ6Z48rService'))->withContext('App\\Controller\\Employe\\ServiceController::show()', $container);
    }
}
