<?php

namespace Container1j8T6gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestimonialTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\TestimonialType' shared autowired service.
     *
     * @return \App\Form\TestimonialType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TestimonialType'] = new \App\Form\TestimonialType(($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container)));
    }
}
