<?php

namespace Container1j8T6gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestimonialRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TestimonialRepository' shared autowired service.
     *
     * @return \App\Repository\TestimonialRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TestimonialRepository'] = new \App\Repository\TestimonialRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
