<?php

namespace ContainerC3hK6LM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GFLsUIgService extends App_KernelRodDebugContainer
{
    /**
     * Gets the private '.service_locator.gFLsUIg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gFLsUIg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Vetreport' => ['privates', '.errored..service_locator.gFLsUIg.App\\Entity\\Vetreport', NULL, 'Cannot autowire service ".service_locator.gFLsUIg": it needs an instance of "App\\Entity\\Vetreport" but this type has been excluded in "config/services.yaml".'],
        ], [
            'Vetreport' => 'App\\Entity\\Vetreport',
        ]);
    }
}
