<?php

namespace ContainerC3hK6LM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVetreportController2Service extends App_KernelRodDebugContainer
{
    /**
     * Gets the public 'App\Controller\Veterinary\VetreportController' shared autowired service.
     *
     * @return \App\Controller\Veterinary\VetreportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Veterinary/VetreportController.php';

        $container->services['App\\Controller\\Veterinary\\VetreportController'] = $instance = new \App\Controller\Veterinary\VetreportController(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\Veterinary\\VetreportController', $container));

        return $instance;
    }
}
