<?php

namespace ContainerC3hK6LM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVetreport2Service extends App_KernelRodDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gFLsUIg.App\Entity\Vetreport' shared service.
     *
     * @return \App\Entity\Vetreport
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gFLsUIg": it needs an instance of "App\\Entity\\Vetreport" but this type has been excluded in "config/services.yaml".');
    }
}
