<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC3hK6LM\App_KernelRodDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC3hK6LM/App_KernelRodDebugContainer.php') {
    touch(__DIR__.'/ContainerC3hK6LM.legacy');

    return;
}

if (!\class_exists(App_KernelRodDebugContainer::class, false)) {
    \class_alias(\ContainerC3hK6LM\App_KernelRodDebugContainer::class, App_KernelRodDebugContainer::class, false);
}

return new \ContainerC3hK6LM\App_KernelRodDebugContainer([
    'container.build_hash' => 'C3hK6LM',
    'container.build_id' => '9eb44fe0',
    'container.build_time' => 1726840287,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC3hK6LM');
