<?php

namespace Container2QcaaQo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalsControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bbmnh0J.App\Controller\AnimalsController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bbmnh0J.App\\Controller\\AnimalsController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'animalRepository' => ['privates', 'App\\Repository\\AnimalRepository', 'getAnimalRepositoryService', true],
            'raceRepository' => ['privates', 'App\\Repository\\RaceRepository', 'getRaceRepositoryService', true],
            'habitatRepository' => ['privates', 'App\\Repository\\HabitatRepository', 'getHabitatRepositoryService', true],
        ], [
            'animalRepository' => 'App\\Repository\\AnimalRepository',
            'raceRepository' => 'App\\Repository\\RaceRepository',
            'habitatRepository' => 'App\\Repository\\HabitatRepository',
        ]))->withContext('App\\Controller\\AnimalsController::index()', $container);
    }
}
