<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1AsahbH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1AsahbH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1AsahbH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1AsahbH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1AsahbH\App_KernelDevDebugContainer([
    'container.build_hash' => '1AsahbH',
    'container.build_id' => 'f4388b91',
    'container.build_time' => 1726813159,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1AsahbH');
