<?php

namespace ContainerZxPxr8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hZ2doBo.App\Controller\Admin\AnimalController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hZ2doBo.App\\Controller\\Admin\\AnimalController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageService' => ['privates', 'App\\Service\\ImageService', 'getImageServiceService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'Motorentity' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'Optionsentity' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'entityManager' => '?',
            'imageService' => 'App\\Service\\ImageService',
            'slugger' => '?',
            'Motorentity' => '?',
            'Optionsentity' => '?',
        ]))->withContext('App\\Controller\\Admin\\AnimalController::new()', $container);
    }
}
