<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1j8T6gu\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1j8T6gu/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container1j8T6gu.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container1j8T6gu\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container1j8T6gu\App_KernelProdContainer([
    'container.build_hash' => '1j8T6gu',
    'container.build_id' => '68cabe28',
    'container.build_time' => 1726840334,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1j8T6gu');
