<?php

namespace Container6QeBmvs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDailydietService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WMseQ83.App\Entity\Dailydiet' shared service.
     *
     * @return \App\Entity\Dailydiet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WMseQ83": it needs an instance of "App\\Entity\\Dailydiet" but this type has been excluded in "config/services.yaml".');
    }
}
