<?php

namespace ContainerXJgDIBj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitatreportControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NuhFOKn.App\Controller\Admin\HabitatreportController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NuhFOKn.App\\Controller\\Admin\\HabitatreportController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'habitatreportepository' => ['privates', 'App\\Repository\\HabitatreportRepository', 'getHabitatreportRepositoryService', true],
        ], [
            'habitatreportepository' => 'App\\Repository\\HabitatreportRepository',
        ]))->withContext('App\\Controller\\Admin\\HabitatreportController::index()', $container);
    }
}
