<?php

namespace ContainerXJgDIBj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVetreportControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QKXNuJ9.App\Controller\Admin\VetreportController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.QKXNuJ9'] ?? $container->load('get_ServiceLocator_QKXNuJ9Service'));

        if (isset($container->privates['.service_locator.QKXNuJ9.App\\Controller\\Admin\\VetreportController::edit()'])) {
            return $container->privates['.service_locator.QKXNuJ9.App\\Controller\\Admin\\VetreportController::edit()'];
        }

        return $container->privates['.service_locator.QKXNuJ9.App\\Controller\\Admin\\VetreportController::edit()'] = $a->withContext('App\\Controller\\Admin\\VetreportController::edit()', $container);
    }
}
