<?php

namespace ContainerRfIPqV0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D5YgLrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D5Yg_lr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D5Yg_lr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\DashboardController::index' => ['privates', '.service_locator._FObXMC.App\\Controller\\Admin\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\Admin\\UserController::index' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\Admin\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\Admin\\UserController::new' => ['privates', '.service_locator.__CzQUd.App\\Controller\\Admin\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\Admin\\UserController::show' => ['privates', '.service_locator.hKA2je_.App\\Controller\\Admin\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\Admin\\UserController::edit' => ['privates', '.service_locator.Qh67eS1.App\\Controller\\Admin\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\Admin\\UserController::delete' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\Admin\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\DashboardController:index' => ['privates', '.service_locator._FObXMC.App\\Controller\\Admin\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\Admin\\UserController:index' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\Admin\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\Admin\\UserController:new' => ['privates', '.service_locator.__CzQUd.App\\Controller\\Admin\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\Admin\\UserController:show' => ['privates', '.service_locator.hKA2je_.App\\Controller\\Admin\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\Admin\\UserController:edit' => ['privates', '.service_locator.Qh67eS1.App\\Controller\\Admin\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\Admin\\UserController:delete' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\Admin\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\DashboardController::index' => '?',
            'App\\Controller\\Admin\\UserController::index' => '?',
            'App\\Controller\\Admin\\UserController::new' => '?',
            'App\\Controller\\Admin\\UserController::show' => '?',
            'App\\Controller\\Admin\\UserController::edit' => '?',
            'App\\Controller\\Admin\\UserController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\DashboardController:index' => '?',
            'App\\Controller\\Admin\\UserController:index' => '?',
            'App\\Controller\\Admin\\UserController:new' => '?',
            'App\\Controller\\Admin\\UserController:show' => '?',
            'App\\Controller\\Admin\\UserController:edit' => '?',
            'App\\Controller\\Admin\\UserController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
