<?php

namespace ContainerQ5xgnED;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRaceControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..fUBbna.App\Controller\Admin\RaceController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..fUBbna.App\\Controller\\Admin\\RaceController::new()'] = ($container->privates['.service_locator..fUBbna'] ?? $container->load('get_ServiceLocator__FUBbnaService'))->withContext('App\\Controller\\Admin\\RaceController::new()', $container);
    }
}
