<?php

namespace ContainerWlSoMEq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestimonialService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ga.aiw8.App\Entity\Testimonial' shared service.
     *
     * @return \App\Entity\Testimonial
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Ga.aiw8": it needs an instance of "App\\Entity\\Testimonial" but this type has been excluded in "config/services.yaml".');
    }
}
