<?php

namespace ContainerE9OWkVf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpeningControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DcatOPi.App\Controller\Admin\OpeningController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DcatOPi.App\\Controller\\Admin\\OpeningController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'opening' => ['privates', '.errored..service_locator.DcatOPi.App\\Entity\\Opening', NULL, 'Cannot autowire service ".service_locator.DcatOPi": it needs an instance of "App\\Entity\\Opening" but this type has been excluded in "config/services.yaml".'],
        ], [
            'opening' => 'App\\Entity\\Opening',
        ]))->withContext('App\\Controller\\Admin\\OpeningController::show()', $container);
    }
}
