<?php

namespace ContainerE9OWkVf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zhttGGF.App\Controller\Admin\ServiceController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.zhttGGF'] ?? $container->load('get_ServiceLocator_ZhttGGFService'));

        if (isset($container->privates['.service_locator.zhttGGF.App\\Controller\\Admin\\ServiceController::delete()'])) {
            return $container->privates['.service_locator.zhttGGF.App\\Controller\\Admin\\ServiceController::delete()'];
        }

        return $container->privates['.service_locator.zhttGGF.App\\Controller\\Admin\\ServiceController::delete()'] = $a->withContext('App\\Controller\\Admin\\ServiceController::delete()', $container);
    }
}
