<?php

namespace ContainerYPbPF0X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitatControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PKLkl9R.App\Controller\Admin\HabitatController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PKLkl9R.App\\Controller\\Admin\\HabitatController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageHabitat' => ['privates', 'App\\Service\\ImageService', 'getImageServiceService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'entityManager' => '?',
            'imageHabitat' => 'App\\Service\\ImageService',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\Admin\\HabitatController::new()', $container);
    }
}
