<?php

namespace ContainerYPbPF0X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitatsControllerdetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nvY2WDd.App\Controller\HabitatsController::details()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nvY2WDd.App\\Controller\\HabitatsController::details()'] = ($container->privates['.service_locator.nvY2WDd'] ?? $container->load('get_ServiceLocator_NvY2WDdService'))->withContext('App\\Controller\\HabitatsController::details()', $container);
    }
}
