<?php

namespace ContainerRqY7NyC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.t3TbjcM.App\Entity\Image' shared service.
     *
     * @return \App\Entity\Image
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.t3TbjcM": it needs an instance of "App\\Entity\\Image" but this type has been excluded in "config/services.yaml".');
    }
}
