<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2QcaaQo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2QcaaQo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2QcaaQo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2QcaaQo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2QcaaQo\App_KernelDevDebugContainer([
    'container.build_hash' => '2QcaaQo',
    'container.build_id' => '116a74b1',
    'container.build_time' => 1726465489,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2QcaaQo');
