<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK6k0oK2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK6k0oK2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK6k0oK2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK6k0oK2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK6k0oK2\App_KernelDevDebugContainer([
    'container.build_hash' => 'K6k0oK2',
    'container.build_id' => 'ed241797',
    'container.build_time' => 1726820131,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK6k0oK2');
