<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vetreport extends \App\Entity\Vetreport implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'animal_id' => [parent::class, 'animal_id', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'detail' => [parent::class, 'detail', null],
        "\0".parent::class."\0".'diet' => [parent::class, 'diet', null],
        "\0".parent::class."\0".'grammage' => [parent::class, 'grammage', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'state' => [parent::class, 'state', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'animal_id' => [parent::class, 'animal_id', null],
        'created_at' => [parent::class, 'created_at', null],
        'detail' => [parent::class, 'detail', null],
        'diet' => [parent::class, 'diet', null],
        'grammage' => [parent::class, 'grammage', null],
        'id' => [parent::class, 'id', null],
        'state' => [parent::class, 'state', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
