<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Testimonial extends \App\Entity\Testimonial implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'active' => [parent::class, 'active', null],
        "\0".parent::class."\0".'comment' => [parent::class, 'comment', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'pseudonym' => [parent::class, 'pseudonym', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'active' => [parent::class, 'active', null],
        'comment' => [parent::class, 'comment', null],
        'created_at' => [parent::class, 'created_at', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'note' => [parent::class, 'note', null],
        'phone' => [parent::class, 'phone', null],
        'pseudonym' => [parent::class, 'pseudonym', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
