<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Animal extends \App\Entity\Animal implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'diet' => [parent::class, 'diet', null],
        "\0".parent::class."\0".'habitat_id' => [parent::class, 'habitat_id', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'images' => [parent::class, 'images', null],
        "\0".parent::class."\0".'medianlife' => [parent::class, 'medianlife', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'race_id' => [parent::class, 'race_id', null],
        "\0".parent::class."\0".'size' => [parent::class, 'size', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'weight' => [parent::class, 'weight', null],
        'created_at' => [parent::class, 'created_at', null],
        'description' => [parent::class, 'description', null],
        'diet' => [parent::class, 'diet', null],
        'habitat_id' => [parent::class, 'habitat_id', null],
        'id' => [parent::class, 'id', null],
        'images' => [parent::class, 'images', null],
        'medianlife' => [parent::class, 'medianlife', null],
        'name' => [parent::class, 'name', null],
        'race_id' => [parent::class, 'race_id', null],
        'size' => [parent::class, 'size', null],
        'slug' => [parent::class, 'slug', null],
        'status' => [parent::class, 'status', null],
        'weight' => [parent::class, 'weight', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
